%2.12 L.D & G.W
%This script blinks the magnetic field
 clear all
basicImports;
clear BiasPsu1;
clear BiasPsu2;
seqUpload(LoadMotSeq(channelTable))
setAHHCurrent(channelTable,'circ',00);
LoadTime = 0.5; %in sec
unLoadTime = 1; %in sec
circCurrent = 70;
pause(2)
FieldOffDelay = 1000;
while 1
    %Turn on magnetic field
%     seqUpload({Pulse(channelTable.PhysicalName{'IGBT_circ'},0,0),...
%     AnalogPulse(channelTable.PhysicalName{'CircCoil'},0,0,circCurrent*10/220)...
%     });
%     pause(LoadTime)
%     %Turn off magnetic field
%     seqUpload({Pulse(channelTable.PhysicalName{'cooling'},0,-1),...
%         Pulse(channelTable.PhysicalName{'repump'},0,-1),...
%         Pulse(channelTable.PhysicalName{'ScopeTrigger'},10,10),...
%         Pulse(channelTable.PhysicalName{'IGBT_circ'},10,-1),...
%     AnalogPulse(channelTable.PhysicalName{'CircCoil'},10,0,0),...
%     Pulse(channelTable.PhysicalName{'cooling'},FieldOffDelay,0)...
%     Pulse(channelTable.PhysicalName{'repump'},FieldOffDelay,0)...
%     });


%     %Turn on magnetic field
    seqUpload({Pulse(channelTable.PhysicalName{'IGBT_circ'},0,0),...
    AnalogPulse(channelTable.PhysicalName{'CircCoil'},0,0,circCurrent*10/220)...
    });
    pause(LoadTime)
    %Turn off magnetic field
    seqUpload({Pulse(channelTable.PhysicalName{'ScopeTrigger'},0,10),...
        Pulse(channelTable.PhysicalName{'IGBT_circ'},0,-1),...
    AnalogPulse(channelTable.PhysicalName{'CircCoil'},0,0,0)...
    });
    %Turn on magnetic field
%     seqUpload({Pulse(channelTable.PhysicalName{'IGBT_rect'},0,0),...
%     AnalogPulse(channelTable.PhysicalName{'RectCoil'},0,0,circCurrent*10/220)...
%     });
%     pause(LoadTime)
%     %Turn off magnetic field
%     seqUpload({Pulse(channelTable.PhysicalName{'ScopeTrigger'},0,10),...
%         Pulse(channelTable.PhysicalName{'IGBT_rect'},0,-1),...
%     AnalogPulse(channelTable.PhysicalName{'RectCoil'},0,0,0)...

% 
%      pause(unLoadTime)
%      setAHHCurrent(channelTable,'circ',circCurrent);
%      pause(LoadTime);
%      setAHHCurrent(channelTable,'circ',0);
%      pause(unLoadTime);
end