function [seq,tend]=TOFseq(channelTable,cameraName,delay,motLoadTime,exposureTime,circCurrent,coolingPower)
%Gal W 080917
%sequence to collect images from the camera connected to trig channel
%delay is the list of times for MOT relase and image in microseconds. 
%default delay =100uS, default mot load time 1 s
%MOT is unloaded 100 mS after the second image is taken
%


if nargin==1
    cameraName='pixelfly';
    delay=1;
    motLoadTime=2e6;
    circCurrent=100;
end

if nargin==2
    delay=1;
    motLoadTime=2e6; 
    circCurrent=100;
end


if nargin==3
    motLoadTime=2e6; 
    circCurrent=100;
end
if strcmp(cameraName,'pixelfly')
    intrinsicDelay=5.6; %microseconds (see manual)
    
end

% exposure=500;
% 
%     seq=[LoadMotSeq(channelTable),...
%          UnloadMotSeq(channelTable,motLoadTime),...
%          {Pulse(channelTable.PhysicalName{'cooling'},motLoadTime+delay,exposureTime),Pulse(channelTable.PhysicalName{'repump'},motLoadTime+delay,exposureTime)},...
%         trigImage(channelTable,motLoadTime+delay-intrinsicDelay,cameraName) 
%         ]; %trigger the image before the intended trigger time to compensate for intrinsic delay


%     seq={AnalogPulse(channelTable.PhysicalName{'IGBT'},0,0,5),... 
%     AnalogPulse(channelTable.PhysicalName{'CircCoil'},0,0,circCurrent*10/220),...
%     Pulse(channelTable.PhysicalName{'cooling'},0,0)...
%     Pulse(channelTable.PhysicalName{'repump'},0,0),...
%     Pulse(channelTable.PhysicalName{'cooling'},motLoadTime-200,-1),...
%     Pulse(channelTable.PhysicalName{'repump'},motLoadTime-200,-1),...
%     Pulse(channelTable.PhysicalName{'ICEEVTTRIG'},motLoadTime-190,1),...
%     AnalogPulse(channelTable.PhysicalName{'IGBT'},motLoadTime,0,0),...
%     AnalogPulse(channelTable.PhysicalName{'CircCoil'},motLoadTime,0,0),...
%     Pulse(channelTable.PhysicalName{cameraName},motLoadTime+delay-intrinsicDelay,20),...
%     Pulse(channelTable.PhysicalName{'cooling'},motLoadTime+delay,exposureTime),...
%     Pulse(channelTable.PhysicalName{'repump'},motLoadTime+delay,exposureTime),...
%     Pulse(channelTable.PhysicalName{'ICEEVTTRIG'},motLoadTime+delay+exposureTime+100,1)
%     }; %trigger the image before the intended trigger time to compensate for intrinsic delay

tStart=0;
[seq,tend]=seqMaker(channelTable,tStart,cameraName,delay(1),motLoadTime,exposureTime,circCurrent,coolingPower);
for ind=2:length(delay)
    [tempseq,tend]=seqMaker(channelTable,tend,cameraName,delay(ind),motLoadTime,exposureTime,circCurrent,coolingPower);
    seq=[seq,tempseq];
end

%     seq={Pulse(channelTable.PhysicalName{'IGBT_circ'},0,0),...
%     AnalogPulse(channelTable.PhysicalName{'CircCoil'},0,0,circCurrent*10/220),...
%     Pulse(channelTable.PhysicalName{'cooling'},0,0)...
%     Pulse(channelTable.PhysicalName{'repump'},0,0),...
%     Pulse(channelTable.PhysicalName{'cooling'},motLoadTime-200,-1),...
%     Pulse(channelTable.PhysicalName{'repump'},motLoadTime-200,-1),...
%     Pulse(channelTable.PhysicalName{'IGBT_circ'},motLoadTime,-1),...
%     AnalogPulse(channelTable.PhysicalName{'CircCoil'},motLoadTime,0,0),...
%     Pulse(channelTable.PhysicalName{cameraName},motLoadTime+delay-intrinsicDelay,20),...
%     Pulse(channelTable.PhysicalName{'cooling'},motLoadTime+delay,exposureTime),...
%     Pulse(channelTable.PhysicalName{'repump'},motLoadTime+delay,exposureTime)
%     }; %trigger the image before the intended trigger time to compensate for intrinsic delay


% Pulse(channelTable.PhysicalName{'ICEEVTTRIG'},motLoadTime,1),...
% Pulse(channelTable.PhysicalName{'ICEEVTTRIG'},motLoadTime+delay+exposureTime,1)

end

function [seq,tend]=seqMaker(channelTable,tStart,cameraName,delay,motLoadTime,exposureTime,circCurrent,coolingPower)
if strcmp(cameraName,'pixelfly')
    intrinsicDelay=5.6; %microseconds (see manual)
    
end

seq={...
    ...%Load MOT
    Pulse(channelTable.PhysicalName{'IGBT_circ'},tStart,0),...
    AnalogPulse(channelTable.PhysicalName{'CircCoil'},tStart,0,circCurrent*10/220),...
    Pulse(channelTable.PhysicalName{'cooling'},tStart,0)...
    Pulse(channelTable.PhysicalName{'repump'},tStart,0),...
    ...%Unload mot
    Pulse(channelTable.PhysicalName{'cooling'},tStart+motLoadTime-200,-1),...
    Pulse(channelTable.PhysicalName{'repump'},tStart+motLoadTime-200,-1),...
    Pulse(channelTable.PhysicalName{'IGBT_circ'},tStart+motLoadTime,-1),...
    AnalogPulse(channelTable.PhysicalName{'CircCoil'},tStart+motLoadTime,0,0),...
    ...%Jump freq, set flash power to 880 and trig
    Pulse(channelTable.PhysicalName{'ICEEVTTRIG'},tStart+motLoadTime+delay-300,1),...
    AnalogPulse(channelTable.PhysicalName{'COOLVVAN'},tStart+motLoadTime+delay-300,0,CoolingPower2AO(880)),...
    Pulse(channelTable.PhysicalName{cameraName},tStart+motLoadTime+delay-intrinsicDelay,20),...
    Pulse(channelTable.PhysicalName{'cooling'},tStart+motLoadTime+delay,0),...
    Pulse(channelTable.PhysicalName{'repump'},tStart+motLoadTime+delay,0),...
    ...%Jump back and set power back
    Pulse(channelTable.PhysicalName{'ICEEVTTRIG'},tStart+motLoadTime+delay+exposureTime+100,1)...
    AnalogPulse(channelTable.PhysicalName{'COOLVVAN'},tStart+motLoadTime+delay+exposureTime+100,0,CoolingPower2AO(coolingPower)),...
    };
tend=tStart+motLoadTime+delay+exposureTime+110;
end

