function b=MOTBlock()
    global p;
    b={'MOT Load',{'IGBT ON'},...
        {'SET CIRC AHH','current',p.circCurrent},...
        {'COOLING ON'},...
        {'REPUMP ON'},...
        {'MOT Load Pause'}
        };
end
